### ISSUE TITLE
[건의] Silence mode 추가

### ISSUE THREAD

**Issue by yoobato** [kakao/olive-cli#2]
olive-cli 실행 시, 아예 아무 로그도 출력되지 않는 silence 모드가 있었으면 좋겠습니다.

현재는 `--debug` 옵션을 통해 디버그용 로그 출력 유무를 설정하고 있는데,
이외에 경과(예. `Commond [init] accomplished.` 등)를 출력 또한 막을 수 있었으면 좋겠습니다.

특히, `analyze`의 경우는 결과가 `json`과 `csv`로 출력되고 있어, 콘솔 창에는 뜨지 않는 옵션이 있었으면 좋겠습니다 :)

혹은, `--debug` 옵션이 아니라, `log=debug` 이런식으로 로그 수준(level)을 지정하도록 하는 것도 좋을 것 같아요.

좋은 도구 만들어주셔서 감사합니다!!!

**Comment by GimunLee** [comment]
@yoobato 
좋은 의견 감사합니다. 긍정적으로 검토해보고 반영할 수 있도록 하겠습니다.
