### ISSUE TITLE
pom.xml 파일이 UNDEFINED 로 분류되는 현상 제보

### ISSUE THREAD

**Issue by yoobato** [kakao/olive-cli#3]
안녕하세요.

pom.xml 파일 파서 분석과 관련하여, `<parent></parent>` 태그가 없으면,
해당 dependency의 type과 package_manager가 **UNDEFINED**로 분류되는 것 같습니다.

아마 olive-cli 프로그램 내부적으로, pom.xml 파일 안에 parent 태그가 없으면,
유효하지 않은 파일로 취급하는 것 같은데요. 확인 좀 부탁드리겠습니다!!!

**Comment by GimunLee** [comment]
안녕하세요. 

관련 내용 확인해보고 말씀드리겠습니다.
제보 감사합니다.

**Comment by oss-kakao** [comment]
@yoobato 
안녕하세요. 

제보해주신 이슈 [v1.2.2](https://github.com/kakao/olive-cli/releases/tag/v1.2.2)에 패치되었습니다.
감사합니다.
