### ISSUE TITLE
[건의] Olive Platform의 서비스 환경 확장

### ISSUE THREAD

**Issue by ymw0407** [kakao/olive-cli#5]
우선 `Olive Platform`과 `olive-cli`라는 좋은 오픈소스 라이선스 검증 서비스를 제공해주셔서 감사합니다!

올리브플랫폼 고객센터에 사용 문의를 한 이후, 오픈소스 라이선스 검증 기능을 `olive-cli`로 다른 오픈소스 프로젝트(웹 서비스)에 적용하려고 하고 있습니다. 현재는 child_process의 형태로 해당 서비스를 사용하려고 하고 있습니다.

그러다보니 해당 서비스를 조금 더 확장시켜서 CLI 환경에서 외부 API 요청을 보내 사용하는 것도 좋지만, npm module과 같은 형태로 직접 실행시킬 수 있도록 하면 더 좋을 것 같다는 생각을 해서 해당 내용을 건의하게 되었습니다!

---
olive-cli에서 좀 더 확장하여 node module의 형태로도 제공하면 외부에서 좀 더 적극적으로 활용할 수 있을 것 같습니다!

**Comment by oss-kakao** [comment]
안녕하세요? 답변이 많이 늦었습니다. ㅠㅠ
OLIVE를 사용하고 좋은 의견 주셔서 감사합니다.
CLI 업데이트시 참고하여 검토 하겠습니다.
