### ISSUE TITLE
[NPM] node_modules 디렉토리 traverse 질문

### ISSUE THREAD

**Issue by yoobato** [kakao/olive-cli#6]
안녕하세요.

우선, Olive CLI를 꾸준히 발전시켜주셔서 정말 감사합니다. 🙇‍♂️

원래 Olive CLI 1.2.0 버전을 쓰다가 이번에 2.x 버전으로 업그레이드해서 사용해보았는데요.

식별되는 오픈소스 S/W 수가 급증해 살펴보던 중,
NPM을 package_manager로 하는 S/W가 다수 식별되면서 수가 증가했다는 사실을 발견했습니다.

혹시, 2.x 버전으로 업그레이드 되면서 node_modules 폴더 내부에 있는 라이브러리들의 `package.json` 파일까지 조회하도록 변경되었을까요?

**Comment by yoobato** [comment]
`node_modules` 디렉토리가 존재할 때, 이 디렉토리의 내부를 탐색하는 것은 곧 Transitive dependency를 식별하는 것이라고 생각이 드는데, 제 생각이 맞으려나요!? 😅

**Comment by yoobato** [comment]
만약, 그렇다면 `analyze` 명령을 통해 생성되는 `dependency.json` 파일에 Direct / Transitive dependency 여부를 구분하는건 어떨까요!?

**Comment by Knext** [comment]
말씀해주신 부분을 확인해보니, node_modules는 탐색이 되지 않아야 하는데 탐색되고 있는 상황입니다.
의견 주신 것처럼 node_modules 디렉토리 탐색은 Transitive dependency에 해당합니다.
현재 관련해서 원인 확인해서 수정진행중이며, 수정 완료되는 대로 새로운 버전으로 배포하도록 하겠습니다.

추가로 Direct 뿐만 아니라 Transitive Dependency 를 제공하는기능 확장을 검토중에 있습니다.
OLIVE CLI 사용 피드백 고맙습니다.

**Comment by yoobato** [comment]
`2.1.0`으로 업데이트된 것 확인했습니다 :)
필요에 따라, 이 이슈는 close해주셔도 될 것 같습니다!

**Comment by Knext** [comment]
확인 고맙습니다. 이 이슈는 종료처리 하겠습니다.
